FROM python:3.11-slim

RUN apt-get update && apt-get install -y --no-install-recommends \
    libgl1 libglib2.0-0 libusb-1.0-0 \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY requirements-edge.txt .
RUN pip install --no-cache-dir -r requirements-edge.txt

COPY . .

CMD ["python", "mainoak.py"]
