apiVersion: 1

datasources:
  - name: SmartWaste PostgreSQL
    type: postgres
    access: proxy
    url: postgres:5432
    database: smartwaste
    user: smartwaste
    secureJsonData:
      password: smartwaste
    jsonData:
      sslmode: disable
      maxOpenConns: 5
      postgresVersion: 1600
    isDefault: true
